/*
	<파일 생성 정보>
	  * 파일 생성일 : 2025.06.08
	  * 대상 파일   : 06_EVTC387 프로젝트별 INV HW 사양 전변설_1.db
	  * 생성 시 발견된 오류 리스트
		 >> 발견된 오류가 없습니다
*/

/********************************************************************************************
*                                   H E A D E R   F I L E                                   *
*                             (C) by Hyundai Motor Company LTD.                             *
********************************************************************************************/

/*===========================================================================================
		Origanization
===========================================================================================*/
/**
	@file		:	InvCfg.h
	@brief		:	
	@author		:	JY.Park
	@date		:	

*/
/*=========================================================================================*/

#ifndef _INVCFG_H_
#define _INVCFG_H_

/*===========================================================================================
	INCLUDES
===========================================================================================*/
#include "common.h"

/*===========================================================================================
	DEFINES
===========================================================================================*/

#if (_PROJECT_NAME == _MV_RWD_PROJ)

	/*-------------------------------------------------------------------------------------------
		@name	: 출력 타입에 의한 사양 구분
	-------------------------------------------------------------------------------------------*/
	
	#if (_PERFORMANCE_TYPE == _STANDARD_VERSION || _PERFORMANCE_TYPE == _PERFORMANCE_VERSION || _PERFORMANCE_TYPE == _LONG_RANGE_VERSION || _PERFORMANCE_TYPE == _eM_160kW_VERSION || _PERFORMANCE_TYPE == _eM_200kW_VERSION || _PERFORMANCE_TYPE == _eM_250kW_VERSION)
		/*-------------------------------------------------------------------------------------------
			@name	: 단계별 Cal 사양 구분
		-------------------------------------------------------------------------------------------*/
	
		#if (_DEVELOPMENT_PHASE == _TCAR_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// MV/RWD/160kW/TCAR
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE						// MV/RWD/160kW/TCAR
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_400A_SCALE_HALL				// MV/RWD/160kW/TCAR
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// MV/RWD/160kW/TCAR
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1		// MV/RWD/160kW/TCAR
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE1		// MV/RWD/160kW/TCAR
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_135_150_DEG_12K_8K_MV_2STG			// MV/RWD/160kW/TCAR
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_				// MV/RWD/160kW/TCAR
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// MV/RWD/160kW/TCAR
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_NOT_INCLUDED	// MV/RWD/160kW/TCAR
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// MV/RWD/160kW/TCAR
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// MV/RWD/160kW/TCAR
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// MV/RWD/160kW/TCAR
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_2	// MV/RWD/160kW/TCAR
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/TCAR
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/TCAR
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// MV/RWD/160kW/TCAR
			#define	_IGU_CAN_VER				_IGU_CAN_AS_INTEG				// MV/RWD/160kW/TCAR
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// MV/RWD/160kW/TCAR
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// MV/RWD/160kW/TCAR
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// MV/RWD/160kW/TCAR
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// MV/RWD/160kW/TCAR
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// MV/RWD/160kW/TCAR
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/TCAR
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/TCAR
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_2				// MV/RWD/160kW/TCAR
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// MV/RWD/160kW/TCAR
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/TCAR
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/TCAR
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _PROTO_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// MV/RWD/160kW/PROTO
			#define	_POWER_MODULE_TYPE				_PM_MV_TYPE							// MV/RWD/160kW/PROTO
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_400A_SCALE_SHUNT_TYPE1			// MV/RWD/160kW/PROTO
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// MV/RWD/160kW/PROTO
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE2		// MV/RWD/160kW/PROTO
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// MV/RWD/160kW/PROTO
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_137_147_DEG_11K_7K_MV_2STG_PROTO	// MV/RWD/160kW/PROTO
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_6kHz_				// MV/RWD/160kW/PROTO
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// MV/RWD/160kW/PROTO
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// MV/RWD/160kW/PROTO
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// MV/RWD/160kW/PROTO
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// MV/RWD/160kW/PROTO
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// MV/RWD/160kW/PROTO
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_2	// MV/RWD/160kW/PROTO
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/PROTO
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/PROTO
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// MV/RWD/160kW/PROTO
			#define	_IGU_CAN_VER				_IGU_CAN_AS_INTEG				// MV/RWD/160kW/PROTO
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// MV/RWD/160kW/PROTO
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// MV/RWD/160kW/PROTO
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// MV/RWD/160kW/PROTO
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// MV/RWD/160kW/PROTO
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// MV/RWD/160kW/PROTO
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/PROTO
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/PROTO
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_2				// MV/RWD/160kW/PROTO
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// MV/RWD/160kW/PROTO
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/PROTO
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/PROTO
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _MASTER_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// MV/RWD/160kW/MASTER
			#define	_POWER_MODULE_TYPE				_PM_MV_TYPE							// MV/RWD/160kW/MASTER
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_400A_SCALE_SHUNT_TYPE1			// MV/RWD/160kW/MASTER
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// MV/RWD/160kW/MASTER
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE2		// MV/RWD/160kW/MASTER
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// MV/RWD/160kW/MASTER
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_137_147_DEG_11K_7K_MV_2STG_PROTO	// MV/RWD/160kW/MASTER
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_6kHz_				// MV/RWD/160kW/MASTER
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// MV/RWD/160kW/MASTER
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// MV/RWD/160kW/MASTER
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// MV/RWD/160kW/MASTER
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// MV/RWD/160kW/MASTER
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// MV/RWD/160kW/MASTER
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_7	// MV/RWD/160kW/MASTER
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/MASTER
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/MASTER
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// MV/RWD/160kW/MASTER
			#define	_IGU_CAN_VER				_IGU_CAN_AS_INTEG				// MV/RWD/160kW/MASTER
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// MV/RWD/160kW/MASTER
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// MV/RWD/160kW/MASTER
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// MV/RWD/160kW/MASTER
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// MV/RWD/160kW/MASTER
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// MV/RWD/160kW/MASTER
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/MASTER
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/MASTER
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_2				// MV/RWD/160kW/MASTER
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// MV/RWD/160kW/MASTER
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/MASTER
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/MASTER
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _PILOT_1_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// MV/RWD/160kW/PILOT_1
			#define	_POWER_MODULE_TYPE				_PM_MV_TYPE							// MV/RWD/160kW/PILOT_1
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_400A_SCALE_SHUNT_TYPE1			// MV/RWD/160kW/PILOT_1
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// MV/RWD/160kW/PILOT_1
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE2		// MV/RWD/160kW/PILOT_1
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// MV/RWD/160kW/PILOT_1
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_137_147_DEG_11K_7K_MV_2STG_PROTO	// MV/RWD/160kW/PILOT_1
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_SVPWMEnb		// MV/RWD/160kW/PILOT_1
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// MV/RWD/160kW/PILOT_1
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// MV/RWD/160kW/PILOT_1
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// MV/RWD/160kW/PILOT_1
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// MV/RWD/160kW/PILOT_1
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// MV/RWD/160kW/PILOT_1
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_8	// MV/RWD/160kW/PILOT_1
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/PILOT_1
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/PILOT_1
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// MV/RWD/160kW/PILOT_1
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// MV/RWD/160kW/PILOT_1
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// MV/RWD/160kW/PILOT_1
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// MV/RWD/160kW/PILOT_1
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// MV/RWD/160kW/PILOT_1
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// MV/RWD/160kW/PILOT_1
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// MV/RWD/160kW/PILOT_1
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/PILOT_1
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/PILOT_1
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_2				// MV/RWD/160kW/PILOT_1
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// MV/RWD/160kW/PILOT_1
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/PILOT_1
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/PILOT_1
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _PILOT_2_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// MV/RWD/160kW/PILOT_2
			#define	_POWER_MODULE_TYPE				_PM_MV_TYPE							// MV/RWD/160kW/PILOT_2
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_400A_SCALE_SHUNT_TYPE1			// MV/RWD/160kW/PILOT_2
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// MV/RWD/160kW/PILOT_2
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE2		// MV/RWD/160kW/PILOT_2
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// MV/RWD/160kW/PILOT_2
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_137_147_DEG_11K_7K_MV_2STG_PROTO	// MV/RWD/160kW/PILOT_2
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_SVPWMEnb		// MV/RWD/160kW/PILOT_2
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// MV/RWD/160kW/PILOT_2
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// MV/RWD/160kW/PILOT_2
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// MV/RWD/160kW/PILOT_2
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// MV/RWD/160kW/PILOT_2
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// MV/RWD/160kW/PILOT_2
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_8	// MV/RWD/160kW/PILOT_2
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/PILOT_2
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/PILOT_2
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// MV/RWD/160kW/PILOT_2
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// MV/RWD/160kW/PILOT_2
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// MV/RWD/160kW/PILOT_2
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// MV/RWD/160kW/PILOT_2
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// MV/RWD/160kW/PILOT_2
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// MV/RWD/160kW/PILOT_2
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// MV/RWD/160kW/PILOT_2
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/PILOT_2
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/PILOT_2
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_2				// MV/RWD/160kW/PILOT_2
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// MV/RWD/160kW/PILOT_2
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/PILOT_2
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/PILOT_2
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _M_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// MV/RWD/160kW/M
			#define	_POWER_MODULE_TYPE				_PM_MV_TYPE							// MV/RWD/160kW/M
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_400A_SCALE_SHUNT_TYPE1			// MV/RWD/160kW/M
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// MV/RWD/160kW/M
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE2		// MV/RWD/160kW/M
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// MV/RWD/160kW/M
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_137_147_DEG_11K_7K_MV_2STG_PROTO	// MV/RWD/160kW/M
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_SVPWMEnb		// MV/RWD/160kW/M
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// MV/RWD/160kW/M
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// MV/RWD/160kW/M
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// MV/RWD/160kW/M
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// MV/RWD/160kW/M
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// MV/RWD/160kW/M
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_11	// MV/RWD/160kW/M
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/M
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/M
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// MV/RWD/160kW/M
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// MV/RWD/160kW/M
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// MV/RWD/160kW/M
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// MV/RWD/160kW/M
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// MV/RWD/160kW/M
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// MV/RWD/160kW/M
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// MV/RWD/160kW/M
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/M
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/M
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_2				// MV/RWD/160kW/M
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// MV/RWD/160kW/M
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_200A_800V_350A	// MV/RWD/160kW/M
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_200A_800V_350A	// MV/RWD/160kW/M
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _SOP_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// MV/RWD/160kW/SOP
			#define	_POWER_MODULE_TYPE				_PM_MV_TYPE							// MV/RWD/160kW/SOP
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_400A_SCALE_SHUNT_TYPE1			// MV/RWD/160kW/SOP
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// MV/RWD/160kW/SOP
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE2		// MV/RWD/160kW/SOP
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// MV/RWD/160kW/SOP
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_137_147_DEG_11K_7K_MV_2STG_PROTO	// MV/RWD/160kW/SOP
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_SVPWMEnb		// MV/RWD/160kW/SOP
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// MV/RWD/160kW/SOP
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// MV/RWD/160kW/SOP
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// MV/RWD/160kW/SOP
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// MV/RWD/160kW/SOP
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// MV/RWD/160kW/SOP
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_11	// MV/RWD/160kW/SOP
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/SOP
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/SOP
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// MV/RWD/160kW/SOP
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// MV/RWD/160kW/SOP
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// MV/RWD/160kW/SOP
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// MV/RWD/160kW/SOP
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// MV/RWD/160kW/SOP
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// MV/RWD/160kW/SOP
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// MV/RWD/160kW/SOP
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/SOP
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/SOP
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_2				// MV/RWD/160kW/SOP
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// MV/RWD/160kW/SOP
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_200A_800V_350A	// MV/RWD/160kW/SOP
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_200A_800V_350A	// MV/RWD/160kW/SOP
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _RC_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// MV/RWD/160kW/RC
			#define	_POWER_MODULE_TYPE				_PM_MV_TYPE							// MV/RWD/160kW/RC
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_400A_SCALE_SHUNT_TYPE1			// MV/RWD/160kW/RC
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// MV/RWD/160kW/RC
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE2		// MV/RWD/160kW/RC
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// MV/RWD/160kW/RC
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_137_147_DEG_11K_7K_MV_2STG_PROTO	// MV/RWD/160kW/RC
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_SVPWMEnb		// MV/RWD/160kW/RC
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// MV/RWD/160kW/RC
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// MV/RWD/160kW/RC
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// MV/RWD/160kW/RC
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// MV/RWD/160kW/RC
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// MV/RWD/160kW/RC
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_14	// MV/RWD/160kW/RC
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/RC
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// MV/RWD/160kW/RC
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// MV/RWD/160kW/RC
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// MV/RWD/160kW/RC
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// MV/RWD/160kW/RC
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// MV/RWD/160kW/RC
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// MV/RWD/160kW/RC
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// MV/RWD/160kW/RC
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// MV/RWD/160kW/RC
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/RC
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// MV/RWD/160kW/RC
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_2				// MV/RWD/160kW/RC
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// MV/RWD/160kW/RC
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/RC
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// MV/RWD/160kW/RC
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
	#else
		#error undefined _DEVELOPMENT_PHASE MACRO
	
	#endif
	#else
		#error undefined _PERFORMANCE_TYPE MACRO
	
	#endif

#elif (_PROJECT_NAME == _NEN_RWD_PROJ)

	/*-------------------------------------------------------------------------------------------
		@name	: 출력 타입에 의한 사양 구분
	-------------------------------------------------------------------------------------------*/
	
	#if (_PERFORMANCE_TYPE == _STANDARD_VERSION || _PERFORMANCE_TYPE == _PERFORMANCE_VERSION || _PERFORMANCE_TYPE == _LONG_RANGE_VERSION || _PERFORMANCE_TYPE == _eM_160kW_VERSION || _PERFORMANCE_TYPE == _eM_200kW_VERSION || _PERFORMANCE_TYPE == _eM_250kW_VERSION)
		/*-------------------------------------------------------------------------------------------
			@name	: 단계별 Cal 사양 구분
		-------------------------------------------------------------------------------------------*/
	
		#if (_DEVELOPMENT_PHASE == _TCAR_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6							// NEN/RWD/160kW/TCAR
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE							// NEN/RWD/160kW/TCAR
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_850A_SCALE_HALL					// NEN/RWD/160kW/TCAR
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL			// NEN/RWD/160kW/TCAR
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1			// NEN/RWD/160kW/TCAR
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE1			// NEN/RWD/160kW/TCAR
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_135_155_DEG_12K_10K_CV_2STG_PILOT2		// NEN/RWD/160kW/TCAR
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_					// NEN/RWD/160kW/TCAR
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM					// NEN/RWD/160kW/TCAR
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED			// NEN/RWD/160kW/TCAR
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW								// NEN/RWD/160kW/TCAR
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1								// NEN/RWD/160kW/TCAR
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1					// NEN/RWD/160kW/TCAR
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_1	// NEN/RWD/160kW/TCAR
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/TCAR
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/TCAR
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// NEN/RWD/160kW/TCAR
			#define	_IGU_CAN_VER				_IGU_CAN_AS_INTEG				// NEN/RWD/160kW/TCAR
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// NEN/RWD/160kW/TCAR
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// NEN/RWD/160kW/TCAR
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// NEN/RWD/160kW/TCAR
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// NEN/RWD/160kW/TCAR
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// NEN/RWD/160kW/TCAR
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/TCAR
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/TCAR
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_1				// NEN/RWD/160kW/TCAR
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// NEN/RWD/160kW/TCAR
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_350A_800V_350A	// NEN/RWD/160kW/TCAR
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// NEN/RWD/160kW/TCAR
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _PROTO_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// NEN/RWD/160kW/PROTO
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE						// NEN/RWD/160kW/PROTO
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_850A_SCALE_HALL				// NEN/RWD/160kW/PROTO
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// NEN/RWD/160kW/PROTO
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1		// NEN/RWD/160kW/PROTO
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// NEN/RWD/160kW/PROTO
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_145_155_DEG_12K_10K_NeN_PROTO1		// NEN/RWD/160kW/PROTO
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_				// NEN/RWD/160kW/PROTO
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// NEN/RWD/160kW/PROTO
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// NEN/RWD/160kW/PROTO
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// NEN/RWD/160kW/PROTO
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// NEN/RWD/160kW/PROTO
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// NEN/RWD/160kW/PROTO
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_1	// NEN/RWD/160kW/PROTO
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/PROTO
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/PROTO
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// NEN/RWD/160kW/PROTO
			#define	_IGU_CAN_VER				_IGU_CAN_AS_INTEG				// NEN/RWD/160kW/PROTO
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// NEN/RWD/160kW/PROTO
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// NEN/RWD/160kW/PROTO
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// NEN/RWD/160kW/PROTO
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// NEN/RWD/160kW/PROTO
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// NEN/RWD/160kW/PROTO
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/PROTO
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/PROTO
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_1				// NEN/RWD/160kW/PROTO
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// NEN/RWD/160kW/PROTO
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_350A_800V_350A	// NEN/RWD/160kW/PROTO
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// NEN/RWD/160kW/PROTO
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _MASTER_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// NEN/RWD/160kW/MASTER
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE						// NEN/RWD/160kW/MASTER
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_850A_SCALE_HALL				// NEN/RWD/160kW/MASTER
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// NEN/RWD/160kW/MASTER
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1		// NEN/RWD/160kW/MASTER
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// NEN/RWD/160kW/MASTER
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_145_155_DEG_12K_10K_NeN_PROTO1		// NEN/RWD/160kW/MASTER
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_				// NEN/RWD/160kW/MASTER
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// NEN/RWD/160kW/MASTER
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// NEN/RWD/160kW/MASTER
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// NEN/RWD/160kW/MASTER
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// NEN/RWD/160kW/MASTER
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// NEN/RWD/160kW/MASTER
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_1	// NEN/RWD/160kW/MASTER
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/MASTER
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/MASTER
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// NEN/RWD/160kW/MASTER
			#define	_IGU_CAN_VER				_IGU_CAN_AS_INTEG				// NEN/RWD/160kW/MASTER
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// NEN/RWD/160kW/MASTER
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// NEN/RWD/160kW/MASTER
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// NEN/RWD/160kW/MASTER
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// NEN/RWD/160kW/MASTER
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// NEN/RWD/160kW/MASTER
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/MASTER
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/MASTER
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_1				// NEN/RWD/160kW/MASTER
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// NEN/RWD/160kW/MASTER
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_350A_800V_350A	// NEN/RWD/160kW/MASTER
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// NEN/RWD/160kW/MASTER
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _PILOT_1_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// NEN/RWD/160kW/PILOT_1
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE						// NEN/RWD/160kW/PILOT_1
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_850A_SCALE_HALL				// NEN/RWD/160kW/PILOT_1
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// NEN/RWD/160kW/PILOT_1
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1		// NEN/RWD/160kW/PILOT_1
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// NEN/RWD/160kW/PILOT_1
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_145_155_DEG_12K_10K_NeN_PROTO1		// NEN/RWD/160kW/PILOT_1
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_				// NEN/RWD/160kW/PILOT_1
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// NEN/RWD/160kW/PILOT_1
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// NEN/RWD/160kW/PILOT_1
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// NEN/RWD/160kW/PILOT_1
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// NEN/RWD/160kW/PILOT_1
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// NEN/RWD/160kW/PILOT_1
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_1	// NEN/RWD/160kW/PILOT_1
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/PILOT_1
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/PILOT_1
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// NEN/RWD/160kW/PILOT_1
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// NEN/RWD/160kW/PILOT_1
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// NEN/RWD/160kW/PILOT_1
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// NEN/RWD/160kW/PILOT_1
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// NEN/RWD/160kW/PILOT_1
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// NEN/RWD/160kW/PILOT_1
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// NEN/RWD/160kW/PILOT_1
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/PILOT_1
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/PILOT_1
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_1				// NEN/RWD/160kW/PILOT_1
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// NEN/RWD/160kW/PILOT_1
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_350A_800V_350A	// NEN/RWD/160kW/PILOT_1
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// NEN/RWD/160kW/PILOT_1
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _PILOT_2_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// NEN/RWD/160kW/PILOT_2
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE						// NEN/RWD/160kW/PILOT_2
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_850A_SCALE_HALL				// NEN/RWD/160kW/PILOT_2
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// NEN/RWD/160kW/PILOT_2
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1		// NEN/RWD/160kW/PILOT_2
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// NEN/RWD/160kW/PILOT_2
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_145_155_DEG_12K_10K_NeN_PROTO1		// NEN/RWD/160kW/PILOT_2
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_				// NEN/RWD/160kW/PILOT_2
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// NEN/RWD/160kW/PILOT_2
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// NEN/RWD/160kW/PILOT_2
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// NEN/RWD/160kW/PILOT_2
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// NEN/RWD/160kW/PILOT_2
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// NEN/RWD/160kW/PILOT_2
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_1	// NEN/RWD/160kW/PILOT_2
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/PILOT_2
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/PILOT_2
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// NEN/RWD/160kW/PILOT_2
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// NEN/RWD/160kW/PILOT_2
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// NEN/RWD/160kW/PILOT_2
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// NEN/RWD/160kW/PILOT_2
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// NEN/RWD/160kW/PILOT_2
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// NEN/RWD/160kW/PILOT_2
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// NEN/RWD/160kW/PILOT_2
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/PILOT_2
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/PILOT_2
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_1				// NEN/RWD/160kW/PILOT_2
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// NEN/RWD/160kW/PILOT_2
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_350A_800V_350A	// NEN/RWD/160kW/PILOT_2
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// NEN/RWD/160kW/PILOT_2
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _M_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// NEN/RWD/160kW/M
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE						// NEN/RWD/160kW/M
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_850A_SCALE_HALL				// NEN/RWD/160kW/M
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// NEN/RWD/160kW/M
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1		// NEN/RWD/160kW/M
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// NEN/RWD/160kW/M
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_145_155_DEG_12K_10K_NeN_PROTO1		// NEN/RWD/160kW/M
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_				// NEN/RWD/160kW/M
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// NEN/RWD/160kW/M
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// NEN/RWD/160kW/M
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// NEN/RWD/160kW/M
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// NEN/RWD/160kW/M
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// NEN/RWD/160kW/M
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_1	// NEN/RWD/160kW/M
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/M
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/M
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// NEN/RWD/160kW/M
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// NEN/RWD/160kW/M
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// NEN/RWD/160kW/M
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// NEN/RWD/160kW/M
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// NEN/RWD/160kW/M
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// NEN/RWD/160kW/M
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// NEN/RWD/160kW/M
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/M
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/M
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_1				// NEN/RWD/160kW/M
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// NEN/RWD/160kW/M
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_350A_800V_350A	// NEN/RWD/160kW/M
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// NEN/RWD/160kW/M
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _SOP_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// NEN/RWD/160kW/SOP
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE						// NEN/RWD/160kW/SOP
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_850A_SCALE_HALL				// NEN/RWD/160kW/SOP
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// NEN/RWD/160kW/SOP
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1		// NEN/RWD/160kW/SOP
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// NEN/RWD/160kW/SOP
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_145_155_DEG_12K_10K_NeN_PROTO1		// NEN/RWD/160kW/SOP
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_				// NEN/RWD/160kW/SOP
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// NEN/RWD/160kW/SOP
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// NEN/RWD/160kW/SOP
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// NEN/RWD/160kW/SOP
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// NEN/RWD/160kW/SOP
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// NEN/RWD/160kW/SOP
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_1	// NEN/RWD/160kW/SOP
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/SOP
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/SOP
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// NEN/RWD/160kW/SOP
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// NEN/RWD/160kW/SOP
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// NEN/RWD/160kW/SOP
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// NEN/RWD/160kW/SOP
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// NEN/RWD/160kW/SOP
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// NEN/RWD/160kW/SOP
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// NEN/RWD/160kW/SOP
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/SOP
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/SOP
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_1				// NEN/RWD/160kW/SOP
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// NEN/RWD/160kW/SOP
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_350A_800V_350A	// NEN/RWD/160kW/SOP
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// NEN/RWD/160kW/SOP
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
		#elif (_DEVELOPMENT_PHASE == _RC_VERSION)
			/* 알고리즘 관리 사양 */
			#define	_GATE_IC_TYPE					_GATE_IC_TYPE_6						// NEN/RWD/160kW/RC
			#define	_POWER_MODULE_TYPE				_PM_CVeGT_TYPE						// NEN/RWD/160kW/RC
			#define	_MOT_CUR_SENSOR_TYPE			_MOT_850A_SCALE_HALL				// NEN/RWD/160kW/RC
			#define	_HSG_CUR_SENSOR_TYPE			_DEFAULT_HSG_300A_SCALE_HALL		// NEN/RWD/160kW/RC
			#define	_HVBATT_SENSOR_TYPE				_EV_HVBATT_SENSOR_1000V_TYPE1		// NEN/RWD/160kW/RC
			#define	_NPCAP_SENSOR_TYPE				_EV_NPCAP_SENSOR_1000V_TYPE2		// NEN/RWD/160kW/RC
			#define	_VAR_FSW_BY_JNC_TEMP_OPTION		_145_155_DEG_12K_10K_NeN_PROTO1		// NEN/RWD/160kW/RC
			#define	_HILL_HOLD_FREQ_				_HILL_HOLD_2_5kHz_5kHz_				// NEN/RWD/160kW/RC
			#define	_HILL_HOLD_OEW_PWM_MODE			_HILL_HOLD_OEW_SVPWM				// NEN/RWD/160kW/RC
			#define	_FSW_DERATING_SENTMP_OPTION		_FSW_DERATING_SENTMP_INCLUDED		// NEN/RWD/160kW/RC
			#define	BRD_TO_INV_UVW_SPEC				ABC_TO_UVW							// NEN/RWD/160kW/RC
			#define	BRD_TO_INV_INV12_SPEC			A_TO_INV1							// NEN/RWD/160kW/RC
			#define	_LVBATT_SENSOR_TYPE				_EV_LVBATT_SENSOR_TYPE1				// NEN/RWD/160kW/RC
	
			/* 로직 관리 사양 */
			#define	_SL_THERMAL_MODEL_TYPE		_SL_ITM_2STAGE_MODULE_TYPE_1	// NEN/RWD/160kW/RC
			#define	_SL_EWP_SPEED_BY_INV_TYPE	_SL_EWP_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/RC
			#define	_SL_RAD_SPEED_BY_INV_TYPE	_SL_RAD_SPD_BY_INV_TYPE_1		// NEN/RWD/160kW/RC
			#define	_SL_IGU_OPTION				_SL_IGU_ENABLE					// NEN/RWD/160kW/RC
			#define	_IGU_CAN_VER				_IGU_CAN_AS_TOPBOT				// NEN/RWD/160kW/RC
			#define	UVLO_SIG_TYPE				UVLO_INTEG
			#define	_GATE_SPEED_CHG				_GATE_SPEED_INCLUDED			// NEN/RWD/160kW/RC
			#define	_SL_HSK_TMPSNS_TYPE			_SL_HSK_TMPSNS_NONE				// NEN/RWD/160kW/RC
			#define	_SL_HSK_ESTTMP_BASE_OPTION	_SL_HSK_ESTTMP_BASE_INV1		// NEN/RWD/160kW/RC
			#define	_SL_MG1_CUR_SNS_PHASE		_SL_CUR_UVW_PHASE				// NEN/RWD/160kW/RC
			#define	_SL_INV1_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_ANALOG			// NEN/RWD/160kW/RC
			#define	_SL_INV2_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/RC
			#define	_SL_SPLIT_TEMP_SNS_OPTION	_SL_INV_TEMP_SNS_PWM			// NEN/RWD/160kW/RC
			#define	_SL_TEMP_SNS_TYPE			_SL_TEMP_SNS_TYPE_1				// NEN/RWD/160kW/RC
			#define	CURSNS_DIRECTION			CURSNS_INV1_TO_MOT_DIR			// NEN/RWD/160kW/RC
	
			/* 일본향 충전 전류 사양 이원화 */
	
			#if (_MARKET_VERSION == _JAPAN_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_350A_800V_350A	// NEN/RWD/160kW/RC
	
			#elif (_MARKET_VERSION == _DOMESTIC_VERSION || _MARKET_VERSION == _NORTH_AMERICA_VERSION || _MARKET_VERSION == _EUROPE_VERSION || _MARKET_VERSION == _CHINA_VERSION || _MARKET_VERSION == _COMMON_COUNTRY_VERSION)
				#define	_MULTI_CHG_CUR_LMT_TYPE		_400V_300A_800V_350A	// NEN/RWD/160kW/RC
	
		#else
			#error undefined _MARKET_VERSION MACRO
	
		#endif
	#else
		#error undefined _DEVELOPMENT_PHASE MACRO
	
	#endif
	#else
		#error undefined _PERFORMANCE_TYPE MACRO
	
	#endif

#else

	/* 프로젝트 미선언 Error 삭제 (헤더 세분화 실시) */
	
	/* DEFAULT 선언 Excel 시트 작성 금지! */

#endif


#endif /* #ifndef _INVCFG_H_ */

/********************************************************************************************
*                                        End of File                                        *
********************************************************************************************/
